{
  "cells": [
    {
      "cell_type": "code",
      "metadata": { "id": "main" },
      "source": [
        "# @title 🚀 INICIAR ESTAÇÃO VISUAL (LIMPEZA + MOTOR + TÚNEL)\n",
        "import os, subprocess, time, re, socket\n",
        "\n",
        "def is_port_open(port):\n",
        "    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n",
        "        return s.connect_ex(('localhost', port)) == 0\n",
        "\n",
        "print(\"🧹 1. Limpando processos antigos...\")\n",
        "!pkill -9 -f engine.py\n",
        "!pkill -9 cloudflared\n",
        "!rm -f engine.py*\n",
        "\n",
        "print(\"📦 2. Instalando dependências...\")\n",
        "!pip install -q diffusers transformers accelerate flask flask-cors\n",
        "\n",
        "print(\"📥 3. Baixando motor atualizado...\")\n",
        "!wget -q https://raw.githubusercontent.com/Miraplay2025/Gerador-de-imagem/main/engine.py -O engine.py\n",
        "\n",
        "print(\"⚙️ 4. Iniciando Servidor Flask...\")\n",
        "subprocess.Popen([\"python3\", \"engine.py\"])\n",
        "\n",
        "print(\"⏳ 5. Aguardando a IA carregar (isso pode levar 30s)...\")\n",
        "while not is_port_open(5000):\n",
        "    time.sleep(2)\n",
        "    print(\".\", end=\"\")\n",
        "\n",
        "print(\"\\n✅ Servidor detectado na porta 5000!\")\n",
        "\n",
        "print(\"🌐 6. Ativando Túnel Cloudflare...\")\n",
        "!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb\n",
        "!dpkg -i cloudflared-linux-amd64.deb > /dev/null 2>&1\n",
        "\n",
        "p = subprocess.Popen(['cloudflared', 'tunnel', '--url', 'http://127.0.0.1:5000'], \n",
        "                     stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n",
        "\n",
        "for line in p.stdout:\n",
        "    if \".trycloudflare.com\" in line:\n",
        "        url = re.search(r\"https://[a-zA-Z0-9-]+\\.trycloudflare\\.com\", line)\n",
        "        if url:\n",
        "            print(\"\\n\" + \"=\"*60)\n",
        "            print(f\"🚀 SISTEMA ONLINE: {url.group(0)}\")\n",
        "            print(\"=\"*60)\n",
        "            print(\"MANTENHA ESTA ABA RODOANDO!\")\n",
        "            break\n",
        "\n",
        "# Mantém o processo vivo\n",
        "try:\n",
        "    while True:\n",
        "        time.sleep(100)\n",
        "except KeyboardInterrupt:\n",
        "    print(\"Encerrado.\")"
      ],
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "kernelspec": { "display_name": "Python 3", "name": "python3" }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
